"""add name

Revision ID: 1d740f7852f5
Revises: a2ccf0d17058
Create Date: 2023-07-17 11:53:30.169855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d740f7852f5'
down_revision = 'a2ccf0d17058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_team', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
