"""added more fields

Revision ID: 2d8d52f6ce47
Revises: 1d740f7852f5
Create Date: 2023-07-17 11:58:09.742626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8d52f6ce47'
down_revision = '1d740f7852f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sprite', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('base_exp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_team', schema=None) as batch_op:
        batch_op.drop_column('base_exp')
        batch_op.drop_column('sprite')
        batch_op.drop_column('ability')

    # ### end Alembic commands ###
